/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TSlugImport } from './routes/t.$slug'
import { Route as RSlugImport } from './routes/r.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TSlugRoute = TSlugImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRoute,
} as any)

const RSlugRoute = RSlugImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugImport
      parentRoute: typeof rootRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/r/$slug': typeof RSlugRoute
  '/t/$slug': typeof TSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/r/$slug': typeof RSlugRoute
  '/t/$slug': typeof TSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/r/$slug': typeof RSlugRoute
  '/t/$slug': typeof TSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/r/$slug' | '/t/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/r/$slug' | '/t/$slug'
  id: '__root__' | '/' | '/r/$slug' | '/t/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RSlugRoute: typeof RSlugRoute
  TSlugRoute: typeof TSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RSlugRoute: RSlugRoute,
  TSlugRoute: TSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/r/$slug",
        "/t/$slug"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/r/$slug": {
      "filePath": "r.$slug.jsx"
    },
    "/t/$slug": {
      "filePath": "t.$slug.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
